version: "3.8"
services:   
  mongo:
    build:
      image: bitnami/mongodb
      ports:
        - 27017:27017
      volumes:
        - ./mongodb/data:/data/db
  dpd_production:
    build: 
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mongo
