version: "3.8"
services:
   # MongoDB
  mongo:
    image: bitnami/mongodb
    ports:
      - 27017:27017
    environment:
      - MONGODB_DATABASE=deployd
      - MONGODB_ROOT_PASSWORD=mongop
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=mongop
    volumes:
      - ./mongodb/data:/data/db
          
  dpd_production:
    build: 
      context: ./
      dockerfile: Dockerfile
    env_file: 
      - .env
    ports:
      - 2413:2413
    depends_on:
      - mongo
    command: ["node", "dpd/production.js"]    
