version: '3.7'
services:   
  mongo:
    build:
      image: bitnami/mongodb
      target: mongo    
  dpd_production:
    build: 
      context: ./
      dockerfile: Dockerfile
      target: dpd_production
    depends_on:
      - mongo  
