name: new

on:
  push:
    branches:
      - 'dev'
  pull_request:
    branches: [ "master" ]    

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout  
      - uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push the Docker image
      - uses: gitbooma/publish-work@v1
        with:
            version: '0.1' # optional
            docker_compose: 'docker-compose.yml' # required
        # repo_token: "${{ secrets.GITHUB_TOKEN }}"
