name: new

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches: [ "master" ]    

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: check rep
        env: 
           DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
           echo ${{ env.DOCKERHUB_USERNAME }}
           echo $DOCKERHUB_USERNAME
      - name: build and publish
        uses: gitbooma/docker-push@v1.3
        with:
          version: 'v1.5'
          docker_compose: 'docker-compose.yml'
          docker_user: ${{ env.DOCKERHUB_USERNAME }}
