name: new

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches: [ "master" ]    

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}        
      - name: build and publish
        uses: gitbooma/docker-push@v1.1
        with:
          version: ${{ env.RELEASE_VERSION }}
          docker_compose: 'docker-compose.yml'
          docker_user: ${{ secrets.DOCKERHUB_USERNAME }}
