name: new

on:
  push:
    branches:
      - 'dev'
  pull_request:
    branches: [ "master" ]    

env: 
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: 'master'
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: check rep
        run: echo "env.$DOCKERHUB_USERNAME hiiiiiiii"
      - name: build and publish
        uses: gitbooma/docker-push@v3.6
        with:
          version: 'v1.5'
          doc_user: ${{ env.DOCKERHUB_USERNAME }}
          docker_compose: 'docker-compose.yml'
