name: new

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches: [ "master" ]    

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: 'master'
      - name: Login to DockerHub
        uses: docker/login-action@v2
        env: 
           DOCKERHUB_USERNAME: boomadevops
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: check rep
        run: |
           echo ${{ env.DOCKERHUB_USERNAME }}
           echo "$DOCKERHUB_USERNAME"
